<<<<<<< HEAD
# Generated by Django 2.2 on 2020-01-20 05:12
=======
# Generated by Django 2.1.7 on 2019-12-06 04:10
>>>>>>> c27b0082056f4046bfd20335d73aae5a0e201635

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.TextField()),
                ('name', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200)),
                ('tamil_name', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubItems',
=======
            name='DailyItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DailySubItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
>>>>>>> c27b0082056f4046bfd20335d73aae5a0e201635
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200)),
                ('tamil_name', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
<<<<<<< HEAD
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vessels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.TextField()),
                ('name', models.TextField()),
=======
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.TextField()),
                ('advance', models.IntegerField()),
                ('session', models.TextField()),
                ('total', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('paid', models.BooleanField()),
                ('returned_vessel', models.BooleanField()),
                ('balance', models.IntegerField()),
                ('date_placed', models.DateTimeField(auto_now_add=True)),
                ('date_of_delivery', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neworder.CustomerDetails')),
>>>>>>> c27b0082056f4046bfd20335d73aae5a0e201635
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neworder.Items')),
<<<<<<< HEAD
                ('subitems', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neworder.SubItems')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.TextField()),
                ('advance', models.IntegerField()),
                ('session', models.TextField()),
                ('total', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('returned_vessel', models.BooleanField(default=False)),
                ('balance', models.IntegerField()),
                ('date_placed', models.DateField(auto_now_add=True)),
                ('date_of_delivery', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neworder.CustomerDetails')),
                ('ordered_items', models.ManyToManyField(to='neworder.OrderItem')),
            ],
        ),
=======
            ],
        ),
        migrations.CreateModel(
            name='SubItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200)),
                ('tamil_name', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vessels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subitems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neworder.SubItems'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_items',
            field=models.ManyToManyField(to='neworder.OrderItem'),
        ),
>>>>>>> c27b0082056f4046bfd20335d73aae5a0e201635
        migrations.AddField(
            model_name='items',
            name='subitems',
            field=models.ManyToManyField(to='neworder.SubItems'),
        ),
    ]
