# Generated by Django 2.2 on 2020-01-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySubItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
