# Generated by Django 2.1.7 on 2019-12-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0002_auto_20191206_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyitems',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysubitems',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
