# Generated by Django 2.2 on 2020-01-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0002_dailyitems_dailysubitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
