# Generated by Django 2.1.7 on 2019-12-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0003_auto_20191206_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyitems',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailysubitems',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
